@startuml

:Suchender:
:Helfer:

rectangle FreiwilligenKoordinierung {
    Suchender ---> (Anzeige erstellen)
    Suchender ---> (Benachrichtigungen erhalten)
    Helfer --> (Benachrichtigungen erhalten)
    Helfer --> (Profil bearbeiten)
    Helfer --> (Anfrage zusagen)
}



@enduml