@startuml

:Suchender:
:Helfer:
:Admin:
:User:

User <|-- Suchender
User <|-- Helfer
User <|-- Admin

left to right direction

rectangle FreiwilligenKoordinierung {

    User --> (Benachrichtigungen erhalten)
    User --> (Profil verwalten)
    Suchender ---> (Gesuch erstellen)
    Helfer --> (Angebot erstellen)

    (Gesuch erstellen) --> (Angebot/Gesuch match finden):<<includes>>
    (Angebot erstellen) --> (Angebot/Gesuch match finden):<<includes>>

    Admin --> (Nutzer verwalten)
    Admin --> (Inhalte moderieren)

}

@enduml